### ISSUE TITLE
Companion Assets should use Asset Track instead of just singular "Health" node.

### ISSUE THREAD

**Issue by HAJ523** [rsek/datasworn#5]
Assets use inconsistent trackers.

Companion assets use the format

"Health": X

Invoke uses the more robust:

"Asset Track": {
  "Name"...
  "Max"...
  "Starting Value"...
}

All companions should be updated to use the "Asset Track" so that programmers don't need to add additional special cases for companions.

**Comment by rsek** [comment]
this is another one of those mismatches between my original intent (human-oriented semantic/informational hierarchy, edited as needed by said humans for their own projects, because IDFK what their project needs and the content is pretty stable anyways) and how this project is actually used. my original rationale is that to a human, `"Health": 5` conveys the information much more succinctly and without the added clutter, and as Health is more frequent than all of the other asset tracks put together, the latter made more sense to call out as distinct.

all that said, i've already moved to a format like this for dataforged. the main difference between that implementation and what you describe here is that i don't bother including values that don't differ from the norm (which in the case of asset tracks is the standard set by Health tracks). so, for instance, `"Starting Value"` is only defined when it's something other than the track's maximum. this is a deliberate choice made for my own personal QoL in mantaining it (keeps clutter down and improves readability, etc). alongside that i could include a separate json file describing the 'standard' values/relationships of certain variables to fall back on.
